{
  imports = [
    ./comments.nix
    ./lsp.nix
    ./git.nix
    ./direnv.nix
    ./icons.nix
    ./codeium.nix
    ./neotree.nix
    ./indent.nix
    ./colorizer.nix
    ./format.nix
    ./todo.nix
    ./completion.nix
    ./rainbow-delimiters.nix
    ./treesitter.nix
    ./which-key.nix
    ./telescope.nix
  ];
}
